# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82fffe3d8419fbb358bd89c2325c82bad8db49018df657ab45805b0be29277d121a4f1bb6662924565d22f25e2e97abc3997752c1edef74af36b9d585091986f

test:
  secret_key_base: b805e806e1a7b27a19d3ac0455231806c817e7e1647820e033b6cde551f93e9dd0a69e71e86c297957d1455b851f073ad1e487359d1e837db620f04cf7578359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
